### ISSUE TITLE
App Connector Module - Migrate source code from Kyma repo to the module [EPIC]

### ISSUE THREAD

**Issue by koala7659** [kyma-project/application-connector-manager#114]
We need to migrate following components to be hosted and built directly in application-connector-module repository:

- central-application-connectivity-validator
- central-application-gateway
- compass-runtime-agent (after included into the module) (see #48)
- common component 

AC:
- [x] Come up with a proposal how the new project layout for the ACM could look, including the sources of the Application Connectivity Validator, Application Gateway and Compass Runtime Agent
    - [x] The new layout should also consider the requirements for the kubebuilder framework
    - [x] Review the proposal with the team and agree on the final layout
- [x] Apply the new layout for the ACM repository
- [x] Migrate all three components (see list in description) into the ACM repository (https://github.com/kyma-project/application-connector-manager/issues/267)
- [x] Ensure unit-tests are correctly working after the components were moved to the ACM repository
- [x] Adjust the security configuration within the ACM repository
