### ISSUE TITLE
Create Application Connector module [EPIC]

### ISSUE THREAD

**Issue by franpog859** [kyma-project/application-connector-manager#154]
**Description**

Application Connector needs to be moved to the modular architecture according to [this concept](https://github.com/kyma-project/community/tree/main/concepts/modularization).

**Reasons**

Application Connector should be more independent so that it must be possible to install, upgrade and operate it separately without dependencies on other Kyma modules. 

**Acceptance criteria**

**Release 1.0.0:**
- [x] Application Connector module must have self-healing properties.
- [x] Operator's configuration must be defined dedicated CRD
- [x] Module must contain legacy Application Connector Components : Application Gateway and Connectivity Validator.  

**Release 1.1.0:**
- [x] Module must contain all Application Connector Components : Application Gateway, Connectivity Validator, and Compass Runtime Agent.  

Prerequisites:
- [x] kyma-project/kyma#15915
- [x] kyma-project/kyma#16169
- ~kyma-project/kyma#15526~ - Not needed for GA

Workplan:
- [x] kyma-project/kyma#15864
- [x] Prepare pipeline for building, testing, linting
- [x] kyma-project/application-connector-manager/issues/29

Until the end of September, Release MVP: 
- [x] kyma-project/application-connector-manager/issues/18
- [x] kyma-project/application-connector-manager/issues/24
- [x] kyma-project/application-connector-manager/issues/6
- [x] kyma-project/application-connector-manager/issues/23
- [x] kyma-project/application-connector-manager#7
- [x] kyma-project/application-connector-manager/issues/31
- [x] kyma-project/application-connector-manager/issues/64
- [x] kyma-project/application-connector-manager/issues/34
- [x] kyma-project/application-connector-manager/issues/21
- [x] kyma-project/application-connector-manager/issues/19
- [x] kyma-project/application-connector-manager/issues/36
- [x] https://github.com/kyma-project/application-connector-manager/pull/88

Release required tasks, until 25 October: **Milestone 1.0.0**
- [x] Testing on stage completed
- [x] 4 Golden signals agreed to be treated as monitoring dashboard
- [x] kyma-project/application-connector-manager/issues/20
- [x] Complete all microdelivery tasks 
- [x] https://github.com/kyma-project/kyma/pull/18312

Release hardening, ~~until mid of November~~: **Milestone 1.1.0**
- [x] kyma-project/application-connector-manager/issues/87
- [x] kyma-project/application-connector-manager/issues/48
- [x] kyma-project/application-connector-manager/issues/53
- [x] kyma-project/application-connector-manager/issues/27
- [x] kyma-project/application-connector-manager/issues/17
- [x] kyma-project/application-connector-manager/issues/41

Consider to close as non-relevant:
- [x] kyma-project/kyma/issues/17993
- [x] kyma-project/application-connector-manager/issues/40
- [x] kyma-project/kyma/issues/17992

**Additional information**
- Related issues for delivery process E2E and making the module production ready for KEDA: 
  - https://github.com/kyma-project/kyma/issues/16494
  - https://github.com/kyma-project/kyma/issues/16550

**Comment by tobiscr** [comment]
Done
