### ISSUE TITLE
App Connector Module - Add Runtime Agent [EPIC] 

### ISSUE THREAD

**Issue by koala7659** [kyma-project/application-connector-manager#48]
**Description**

After Enabling Compass Manager on KCP we are finally ready to make Runtime Agent the part of Application Connector module.  

This task will include:

Required for first release:
- [x] Insert manifests for Runtime Agent to .yaml file managed by  `application-connector-manager`
- [x] Add code to enable and disable Runtime Agent deployment based on the existence of a secret `compass-agent-configuration` (the Compass Runtime Agent's deployment is scaled to zero when the secret with the configuration doesn't exist)
  - [x] [PR-202](https://github.com/kyma-project/application-connector-manager/pull/202)
  - [x] code-review
- [x] fixes of tests https://github.com/kyma-project/application-connector-manager/issues/17 (@koala7659 , @m00g3n )
- [x] (can be done in parallel)
  - [x] todo  https://github.com/kyma-project/application-connector-manager/pull/207 (@grego952 )
  - [x] code-review (@mvshao)

Rollout of ACM:
- [x] https://github.com/kyma-project/application-connector-manager/issues/212
- [x] Cleanup
    - [x] Remove Compass Runtime Agent helm chart from installed Kyma Resources (make sure they are not installed an any more)
      - [x] [PR-208](https://github.com/kyma-project/application-connector-manager/pull/208) - Move ACM CRDs from kyma repository
      - [x] [PR-18606](https://github.com/kyma-project/kyma/pull/18606) - Remove compass-runtime-agent from kyma resources
      - [x] code-review
    - [x] #195
